services:
  - type: web
    name: chartz
    env: node
    region: oregon
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
